Feature/fix tsconfig
technology-studio/ignite-txo-package-boilerplate pull request #3
Opened 2020-08-28 06:20 UTC by ondrej-mikulas

2020-08-28 06:33 UTC, erik-slovak commented on boilerplate.typescript.js
> +  { template: 'packages/tsconfig.json.ejs', target: `${packageRelativePath}/tsconfig.json` },
If you're not using any EJS templates in `boilerplate/typescript/packages/tsconfig.json.ejs`, the rename was not necessary. Original `tsconfig.json` file is copied in https://github.com/technology-studio/ignite-txo-package-boilerplate/blob/3ee375e34f68163f8a5d6c5c9dd8e92cb26dbad1/boilerplate.js#L106-L109

2020-08-28 06:51 UTC, erik-slovak approved these changes

2020-08-28 06:54 UTC, rostislav-simonik requested changes

2020-08-28 06:54 UTC, rostislav-simonik commented on boilerplate.typescript.js
> +  { template: 'packages/tsconfig.json.ejs', target: `${packageRelativePath}/tsconfig.json` },
should not be here, there is missing copy command in ignite package function that copy non template files. And it should not have ejs suffix if it's not template.

2020-09-03 06:25 UTC, rostislav-simonik approved these changes

2020-09-03 06:25 UTC, merged